### PR TITLE
fix the timestamp for ishares scraper

### PR DESCRIPTION
**Pull request by cjyetman**

### CODE REVIEW

**Review by jdhoffa — APPROVED** [review]
lgtm

**Comment by cjyetman** [comment]
FYI - devel R now throws a Note in R CMD check (which our CI here considers and error)...
```shell
Problems with news in ‘NEWS.md’:
  No news entries found.
```
don't know how to work around that, especially when there is a NEWS entry
https://github.com/RMI-PACTA/pacta.data.scraping/blob/c7cfaadc6db35039528677a2745426bcd7ae77fd/NEWS.md?plain=1#L1-L3

all other versions pass

**Comment by jdhoffa** [comment]
> pacta.data.scraping/NEWS.md

Ah, this is because there hasn't been a release of `pacta.data.scraping` yet. `NEWS.md` tracks changes for every version number AFTER an initial release, but since there hasn't been a `0.0.1` release yet, there is no news to keep track of. 

I imagine the R CMD Check must be looking through the NEWS file for a semantic version number, and since it doesn't find one it thinks there is no news. 

I think you are safe to just delete the NEWS.md for now.

**Comment by jdhoffa** [comment]
But this PR lgtm. I will delete the file in a separate PR.

**Pull request merged**
